### ISSUE TITLE
Explicitly typed Slice

### ISSUE THREAD

**Issue by grv87** [airlift/slice#112]
I consider using your library for API.
Unfortunately, `Slice` can't be explicitly typed.
If I write `public Slice getValue()`, user can't be sure whether it is a slice of `byte`s, `int`s or something else.
The same for parameters.
This information could be specified in doc. But we still lose type checking from the compiler.

Did you consider having several classes, for each primitive type?

I saw [this comment](https://github.com/airlift/slice/issues/106#issuecomment-425164431), but, maybe, to avoid code duplication, you could have one template and a generator?

**Comment by electrum** [comment]
If you have homogeneous data types, using a primitive array is preferable for several reasons (including the JVM generating better code).

**Comment by dain** [comment]
@grv87 Can you describe the problem you are having?  I ask because one of the points of Slice is to normalize the access to arrays of different types, so I'm not sure this aligns with the purpose of Slice.  Actually, if you know the type of the underlying data ahead of time, you can just use Java VarHandles.

**Comment by grv87** [comment]
I'm porting some code from Go. Go have built-in slices.
If there would be slices implemented in Java then I could port code without significant changes.

Groovy has slice syntax, but it doesn't actually slice, it creates a copy. Copying is inefficient.

I'm porting not just algorithms, but built-in Go packages too. If there would be slices implemented in Java then resulted API would be simpler and more familiar for Go users.
I had a thought that your library could help with that.
But now I see that I could wrap a primitive array in class doing reindexing, and that would be enough.
