### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by dhutchis** [airlift/slice#71]
Is there a place where I can view documentation for this library?  I see it used extensively in [Presto](https://github.com/prestodb/presto), but I wouldn't know where to start if I wanted to use it in my own library.  Is there a place we can see Slice's design and related software?

**Comment by dain** [comment]
The main entry points are Slice, Slices, SliceInputStream, and SliceOutputStream.  The code has pretty extensive Java docs, which you should be able to browse in any IDE.  Is there something more needed.

**Comment by tmm1** [comment]
Link to a java doc html page on github pages or something would be nice.
